<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
           http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.rspereiratech</groupId>
        <artifactId>openapi-collection-generator-parent</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>openapi-collection-generator-samples</artifactId>
    <packaging>pom</packaging>

    <name>OpenAPI Collection Generator - Samples</name>
    <description>Sample project to validate the OpenAPI collection generator plugin.</description>
    <url>https://github.com/rspereiratech/openapi-collection-generator-samples</url>

    <scm>
        <connection>scm:git:git://github.com/rspereiratech/openapi-collection-generator-samples.git</connection>
        <developerConnection>scm:git:ssh://git@github.com/rspereiratech/openapi-collection-generator-samples.git</developerConnection>
        <url>https://github.com/rspereiratech/openapi-collection-generator-samples</url>
        <tag>HEAD</tag>
    </scm>

    <issueManagement>
        <system>GitHub Issues</system>
        <url>https://github.com/rspereiratech/openapi-collection-generator-samples/issues</url>
    </issueManagement>

    <build>
        <plugins>
            <!-- Generate Postman and Insomnia collections -->
            <plugin>
                <groupId>io.github.rspereiratech</groupId>
                <artifactId>openapi-collection-generator-maven-plugin</artifactId>
                <version>1.0.0-SNAPSHOT</version>
                <executions>
                    <execution>
                        <id>generate-collections</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <formats>
                                <format>POSTMAN</format>
                                <format>INSOMNIA</format>
                            </formats>
                            <collectionName>PetStore</collectionName>
                            <outputDirectory>${project.basedir}/collections</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
